# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'J.Codable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for J.Codable
  pod 'Alamofire', '~> 5.1'
  target 'J.CodableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'J.CodableUITests' do
    # Pods for testing
  end

end
